server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.backend.model    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: backend-provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://2501server.com:3306/db_backend?useSSL=false&serverTimezone=UTC             # 数据库名称
    username: wg
    password: a20210415A!
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://2501eureka.com:7001/eureka
       #defaultZone: http://2501eureka.com:7001/eureka/,http://2501eureka.com:7002/eureka/,http://2501eureka.com:7003/eureka/      
  instance:
    instance-id: backend-provider8001
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
info: 
  build.artifactId: $project.artifactId$
  build.version: $project.version$